version: 0.2

phases:
  install:
    commands:
      - echo Node Js Installation In-Progress
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - echo Yarn Installation In-Progress
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  pre_build:
    commands:
      - echo Dependencies Installation In-Progress
      - yarn
  build:
    commands:
      - echo Building Application In-Progress
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist