version: 0.2
env:
  # variables:
  #   REACT_APP_TEST_KEY: "REACT_APP_TEST_VALUE"
  parameter-store:
    REACT_APP_TEST_KEY: REACT_APP_TEST_KEY
phases:
  install:
    commands:
      - echo Node Js Installation In-Progress
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt install -y nodejs
      - echo Yarn Installation In-Progress
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt install --no-install-recommends yarn
  pre_build:
    commands:
      - echo "REACT_APP_TEST_KEY = $REACT_APP_TEST_KEY"
      - echo Dependencies Installation In-Progress
      - yarn
  build:
    commands:
      - echo Building Application In-Progress
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
